drop table telefonos_tab;
drop table boolean_table;
drop table nombres_table;
drop table coordenada_table;
purge recyclebin;
drop table via_table cascade constraints purge;
drop table ruta_table cascade constraints purge;
drop table valoracion_table cascade constraints purge;
drop table hito_table cascade constraints purge; 
drop table ciudad_table cascade constraints purge;
drop table servicio_table cascade constraints purge;
drop table seaccedepor_table cascade constraints purge;
drop table valoraciudad_table cascade constraints purge;
drop table valorahito_table cascade constraints purge;
drop table valoraruta_table cascade constraints purge;
drop table paquete_table cascade constraints purge;
drop table agr_hito_tablet cascade constraints purge;
drop table evento_table cascade constraints purge;
drop table tiene_table cascade constraints purge;
drop table tieneservicio_table cascade constraints purge;
purge recyclebin;
drop table contrata_table cascade constraints purge;
drop table toma_table cascade constraints purge;
drop table usuario_table cascade constraints purge;


-- TYPES
DROP TYPE valoraciudad_t;
DROP TYPE Toma;
DROP TYPE fija_t;
DROP TYPE dinamica_t;
DROP TYPE valorahito_t;
DROP TYPE valoraruta_t;
DROP TYPE SeAccedePor;
DROP TYPE TieneServicio;
DROP TYPE Tiene;
DROP TYPE agr_hito_t;
DROP TYPE valoracion_t ;
purge recyclebin;
DROP TYPE telefono_t FORCE;
DROP TYPE coordenada_t FORCE;
DROP TYPE nombres_t FORCE;
DROP TYPE boolean_t FORCE;
DROP TYPE multis_t FORCE;
DROP TYPE multi_t FORCE;
DROP TYPE usuario_t;
DROP TYPE hito_t;
DROP TYPE ruta_t;
DROP TYPE evento_t;
DROP TYPE servicio_t;
DROP TYPE paquete_t;
DROP TYPE via_t;
DROP TYPE ciudad_t;
DROP TYPE acompanante_t FORCE;
DROP TYPE acompanantes_t ;
drop type refs_to_ruta;
drop type refs_to_evento;
drop type refs_to_via;
drop type contrata_t;
DROP TYPE time_t FORCE;

