CREATE OR REPLACE TYPE  "FuzzyDomain_TYPE" AS OBJECT (
   NameFD varchar(20)
)
NOT FINAL;

CREATE OR REPLACE TYPE  "CARATOMICA_TYPE" UNDER DomDifuso_type (
)
NOT FINAL;

CREATE OR REPLACE TYPE  "SINREPSEM_TYPE" UNDER CarAtomica_type (
)
NOT FINAL;

CREATE OR REPLACE TYPE  "CONREPSEM_TYPE" UNDER CarAtomica_type (
)
NOT FINAL;

CREATE OR REPLACE TYPE  "VALOR_TYPE" AS OBJECT (
   Correl NUMBER,
   v_entero NUMBER,
   v_real NUMBER(12,3),
   v_string VARCHAR2(20)
);

CREATE OR REPLACE TYPE  "CONFINITO_TYPE" AS TABLE OF Valor_type;

CREATE OR REPLACE TYPE  "REFFINITO_TYPE" UNDER ConRepSem_type (
   Nombre_Conjunto varchar2(20), 
   ConFinito ConFinito_type
);

CREATE OR REPLACE TYPE  EtiCon_type AS OBJECT (
   Nombre_EtiCon VARCHAR2(20)
);

CREATE OR REPLACE TYPE TieneGrado_type AS OBJECT (
   Correl Number,
   Nombre_EtiCon VARCHAR2(20),
   grado NUMBER(3,2)
);a


