CREATE OR REPLACE TYPE BODY D_FlexCad AS 
 
 CONSTRUCTOR FUNCTION D_FlexCad (Lab IN VARCHAR2, N1 IN NUMBER, N2 IN NUMBER, N3 IN NUMBER, N4 IN NUMBER) RETURN SELF AS RESULT IS
  BEGIN
    CA_LinLab('FlexCad', Lab, User , N1, N2, N3, N4);
    SELF:=D_FlexCad('FlexCad', Lab, Trapezoid_objtyp(N1, N2, N3, N4));
    RETURN;
  END;

 CONSTRUCTOR FUNCTION D_FlexCad (Lab IN VARCHAR2) RETURN SELF AS RESULT IS
  BEGIN
    SELF:=D_FlexCad('FlexCad', Lab, Trapezoid_objtyp('FlexCad', Lab));
    RETURN;
  END;

 CONSTRUCTOR FUNCTION D_FlexCad (Num IN NUMBER) RETURN SELF AS RESULT IS
  BEGIN
    SELF:=D_FlexCad('FlexCad', NULL , Trapezoid_objtyp('FlexCad', Num));
    RETURN;
  END;

MEMBER FUNCTION LSHOW RETURN VARCHAR2 IS
 BEGIN
  RETURN SELF.Trap.LSHOW('FlexCad');
 END;

MEMBER FUNCTION FEQ (L1 IN VARCHAR2) RETURN REAL IS
  BEGIN
    RETURN SELF.Trap.FEQ('FlexCad',L1);
  END;

END;
/